# baseURL
@baseURL = http://localhost:3000
# @baseURL = http://34.142.237.138

###
# Find All Users
GET {{ baseURL }}/users

###
# Find User By Id
GET {{ baseURL }}/users/634d5efdf9a9d10164563608

###
# Create User
POST {{ baseURL }}/users
Content-Type: application/json

{
    "email": "example@email.com",
    "password": "password"
}

###
# Modify User By Id
PUT {{ baseURL }}/users/634d655df9a9d10164563612
Content-Type: application/json

{
    "email": "example@email.com",
    "password": "password"
}

###
# Delete User By Id
DELETE {{ baseURL }}/users/634d655df9a9d10164563612
